{
 "title": "KSQL DASHBOARD",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "KUBERNETES_NAME",
    "query": "label_values(ksql_metrics_query_stats_running_queries,kubernetes_name)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "KSQL_PERSISTENET_QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_persistent_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_REBALANCING_QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_rebalancing_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_ACTIVE_QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_active_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE_CONSUMED_PER_SECOND",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_consumed_per_sec{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE_CONSUMED_IN_AVERAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_consumed_avg{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE_CONSUMED_PER_MIN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_consumed_min{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_CREATED_QUERIES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_created_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_PENDING_SHUTDOWN_QUESRIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_pending_shutdown_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE_PRODUCED_PER_SECOND",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_produced_per_sec{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_RUNNING_QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_running_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": " [{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE _CONSUMED_TOTAL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_consumed_total{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": " [{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_ERROR QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_error_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": " [{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_MESSAGE_CONSUMED_MAX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_consumed_max{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": " [{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_QUERIES_NOT_RUNNING",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_query_stats_not_running_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "KSQL_IDEL_QUERIES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_metrics_persistent_queries{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  }
 ]
}