{
 "title": "MaxCtrl MaxScale",
 "tags": [
  "mariadb",
  "maxscale"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(maxctrl_server_up, instance)"
   },
   {
    "name": "id",
    "label": "Thread ID",
    "query": "label_values(maxctrl_status_current_descriptors, id)"
   }
  ]
 },
 "panels": [
  {
   "title": "MaxScale Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "maxctrl_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Average Event Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "maxctrl_status_avg_event_queue_length{instance=\"$host\",id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(maxctrl_server_connections{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Read / Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops", "label": "Operations / Sec" }
   ],
   "targets": [
    {
     "expr": "irate(maxctrl_status_read_events{instance=\"$host\",id=\"$id\"}[$interval])",
     "legendFormat": "reads / sec"
    },
    {
     "expr": "irate(maxctrl_status_write_events{instance=\"$host\",id=\"$id\"}[$interval])",
     "legendFormat": "writes / sec"
    }
   ]
  },
  {
   "title": "Event Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maxctrl_status_accept_events{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Accept events"
    },
    {
     "expr": "maxctrl_status_error_events{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Error events"
    },
    {
     "expr": "maxctrl_status_hangup_events{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Hangup events"
    },
    {
     "expr": "maxctrl_status_max_event_exec_time{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Max event exec time"
    }
   ]
  },
  {
   "title": "Event Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "maxctrl_status_max_event_queue_length{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Max Time in Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(maxctrl_status_max_event_queue_time{instance=\"$host\",id=\"$id\"}[$interval])",
     "legendFormat": "Max flight time"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maxctrl_server_connections{instance=\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Service Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "maxctrl_service_current_sessions{instance=\"$host\"}",
     "legendFormat": "Current sessions"
    },
    {
     "expr": "maxctrl_service_total_sessions{instance=\"$host\"}",
     "legendFormat": "Total sessions"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "maxctrl_status_load_last_hour{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Load last hour"
    },
    {
     "expr": "maxctrl_status_load_last_minute{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Load last minute"
    },
    {
     "expr": "maxctrl_status_load_last_second{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Load last second"
    }
   ]
  },
  {
   "title": "Query Classifier Cache",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ops", "label": "ops/sec" }
   ],
   "targets": [
    {
     "expr": "maxctrl_status_query_classifier_cache_evictions{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Evictions"
    },
    {
     "expr": "maxctrl_status_query_classifier_cache_hits{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "maxctrl_status_query_classifier_cache_inserts{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Inserts"
    },
    {
     "expr": "maxctrl_status_query_classifier_cache_misses{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Misses"
    },
    {
     "expr": "maxctrl_status_query_classifier_cache_size{instance=\"$host\",id=\"$id\"}",
     "legendFormat": "Cache size"
    }
   ]
  }
 ]
}