{
 "title": "KAFKA DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount,topic)"
    }
   },
   {
    "name": "Error",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_count,error)"
    }
   },
   {
    "name": "Request",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_errorspersec,request)"
    }
   },
   {
    "name": "Broker",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate,instance)"
    }
   },
   {
    "name": "Zookeeper_SessionState",
    "query": {
     "query": "label_values(kafka_server_sessionexpirelistener_count,name)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "KUBERNETES_NAME",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount, kubernetes_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages In Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_brokertopicmetrics_messagesinpersec{topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (kafka_server_brokertopicmetrics_bytesinpersec[5m])",
     "legendFormat": "{{kubernetes_name}} {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (kafka_server_brokertopicmetrics_bytesoutpersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{kubernetes_name}} {{topic}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesinpersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesoutpersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "ErrorsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(instance) ((kafka_network_requestmetrics_errorspersec{instance=~\"$Broker\", request=~\"$Request\"})))",
     "legendFormat": "[{{kubernetes_name}} {{instance}} ]"
    }
   ]
  },
  {
   "title": "ProducerRequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m]))",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "RequestBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_requestmetrics_requestbytes{kubernetes_name=~\"$KUBERNETES_NAME\",instance=~\"$Broker\"}[5m]))",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Log flush rate and time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_logflushstats_logflushrateandtimems{kubernetes_name=~\"$KUBERNETES_NAME\",quantile=\"\"}",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "OfflineLogDirectoryCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_log_logmanager_offlinelogdirectorycount{kubernetes_name=~\"$KUBERNETES_NAME\"})",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{kubernetes_name=\"$KUBERNETES_NAME\"})",
     "legendFormat": "activecontroller"
    }
   ]
  },
  {
   "title": "PartitionCount across Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(topic) ((kafka_cluster_partition_replicascount{topic!=\"\"})))",
     "legendFormat": "{{topic}} {{instance}}"
    }
   ]
  },
  {
   "title": "UncleanLeaderElectionsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_controllerstats_uncleanleaderelectionspersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] "
    }
   ]
  },
  {
   "title": "IsrExpandsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrexpandspersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "IsrShrinksPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrshrinkspersec{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Requests waiting in the producer purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(kafka_server_delayedoperationpurgatory_numdelayedoperations{kubernetes_name=~\"$KUBERNETES_NAME\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UnderMinIsrPartitionCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underminisrpartitioncount{kubernetes_name=~\"$KUBERNETES_NAME\"} ",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "LeaderElectionRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_controller_controllerstats_leaderelectionrateandtimems{kubernetes_name=~\"$KUBERNETES_NAME\",quantile=\"\"})",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "LeaderCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "MaxLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicafetchermanager_maxlag{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "NetworkProcessorAvgIdlePercent",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_socketserver_networkprocessoravgidlepercent{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_kafkacontroller_offlinepartitionscount{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{topic!=\"\",topic=~\"$Topics\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Topic}}:{{topic}}]"
    }
   ]
  },
  {
   "title": "Produce request rate for requests that failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequestspersec{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[ {{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "RequestQueueSize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestchannel_requestqueuesize{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[ {{kubernetes_name}} {{instance}}]"
    }
   ]
  }
 ]
}