{
 "title": "NODE-METRICS DASHBOARD",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TOPIC",
    "query": "label_values(kafka_log_log_value,topic)"
   },
   {
    "name": "NODE_INSTANCE",
    "query": "label_values(node_network_transmit_bytes_total,instance)"
   },
   {
    "name": "KUBERNETES_NAME",
    "query": "label_values(kafka_server_brokertopicmetrics_count,kubernetes_name)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "node network receive bytes total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\",instance=~\"$NODE_INSTANCE\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} "
    }
   ]
  },
  {
   "title": "node network transmit bytes total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\",instance=~\"$NODE_INSTANCE\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}}"
    }
   ]
  },
  {
   "title": "node disk io now",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"vdb\",instance=~\"$NODE_INSTANCE\"}",
     "legendFormat": "{{broker}}:{{instance}} "
    }
   ]
  },
  {
   "title": "node cpu seconds total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "16-sum(rate(node_cpu_seconds_total{instance=~\"$NODE_INSTANCE\",mode=\"idle\"}[5m]))by (instance)",
     "legendFormat": "{{broker}}:{{instance}}"
    }
   ]
  },
  {
   "title": "jvm threads current",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_threads_current{kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "jvm memory bytes used heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_bytes_used{area=\"heap\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "jvm memory bytes used non heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_bytes_used{area=\"nonheap\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec Kafka",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\",topic!=\"\",topic=~\"$TOPIC\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec Kafka",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\",topic=~\"$TOPIC\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "Replication Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_meanrate{name=\"ReplicationBytesOutPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}}   {{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Messages In Per Sec Kafka",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\",topic!=\"\",topic=~\"$TOPIC\"}[5m])",
     "legendFormat": "{{broker}}:{{instance}} {{topic}}"
    }
   ]
  }
 ]
}