{
 "title": "NEW ZOOKEEPER",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "Zookeeper",
    "query": "label_values(zookeeper_PacketsSent,kubernetes_name)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Sent rate",
   "type": "graph",
   "description": "Number of client packets sent (responses and notifications).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "-rate(zookeeper_PacketsSent{kubernetes_name=~\"$Zookeeper\"}[5m])",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Received rate",
   "type": "graph",
   "description": "Number of client packets received (responses and notifications).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_PacketsReceived{kubernetes_name=~\"$Zookeeper\"}[5m])",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "description": "Number of watchers setup over Zookeeper nodes.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_InMemoryDataTree_WatchCount{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "description": "Number of znodes in the Zookeeper namespace.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_InMemoryDataTree_NodeCount{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Request avg. latency",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request (since the server was started).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_AvgRequestLatency{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_SyncLimit{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Election Time Taken",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_ElectionTimeTaken{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_OutstandingRequests{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "MIN SESSION TIME OUT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_MinSessionTimeout{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "MAX SESSION TIME OUT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_MaxSessionTimeout{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "INIT LIMIT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_InitLimit{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "TICK TIME",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_TickTime{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  },
  {
   "title": "Alive connection count",
   "type": "graph",
   "description": "Number of active, connected sessions.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_NumAliveConnections{kubernetes_name=~\"$Zookeeper\"}",
     "legendFormat": "replica-{{replicaId}} ({{memberType}}) [{{kubernetes_name}} ({{instance}})]"
    }
   ]
  }
 ]
}